CNN 1
Assume that a CNN processes data samples of size (32,32,3). Furthermore
assume the following structure for the first 6 layers:
ˆ Conv2D with filter size 3x3, strides 1x1 and 32 filters
ˆ ReLU
ˆ MaxPooling2D with kernel size 2x2
ˆ Conv2D with filter size 4x4, strides 1x1 and 64 filters
ˆ ReLU
ˆ MaxPooling2D with kernel size 2x2
Please give the dimensions of the first 6 layers as tuples of (H, W, C)!

    Conv2D layer: (30, 30, 32) (assuming "valid" padding is used)
    ReLU: (30, 30, 32)
    MaxPooling2D layer: (15, 15, 32)
    Conv2D layer: (12, 12, 64) (assuming "valid" padding is used)
    ReLU: (12, 12, 64)
    MaxPooling2D layer: (6, 6, 64)

CNN 2
Please give a list of keras layer types and their parameters that would typically
be used to perform classification on 28x28x3 image data! There should be at
least one convolutional layer and at least two dense (affine) layers!

In [ ]:
keras.layers.Conv2D(32, (3,3), activation='relu', input_shape=(28, 28, 3))
    # 32: number of filters
    # (3, 3): kernel size
    # activation: ReLU activation function
    # input_shape: shape of input data (28, 28, 3)
keras.layers.MaxPooling2D((2,2))
    # (2, 2): pool size
keras.layers.Flatten()
    # flattens the output from previous layer into a 1D tensor
keras.layers.Dense(128, activation='relu')
    # 128: number of neurons
    # activation: ReLU activation function
keras.layers.Dense(10, activation='softmax')
    # 10: number of neurons (corresponding to the number of classes)
    # activation: softmax activation function to produce a probability distribution over the classes.

CNN 3
Please mark the following statements with true or false, no justification required!
ˆ All filters in a Conv2D-layer must be identical
ˆ The number of filters in a conv2D-layer can be chosen arbitrarily
ˆ The width and height of a conv2D-layer output can be chosen arbitrarily
ˆ A max-pooling layer must have a kernel size of 2x2
ˆ A Conv2D-layer must be followed by ReLU
ˆ A CNN classifier must contain at least one affine layer
ˆ A CNN classifier can contain an arbitrary number of Conv2D-layers

   - All filters in a Conv2D-layer must be identical: 
   False. 
   Filters in a Conv2D layer can be different and are learned during the training process. 
   The purpose of filters is to extract different features from the input data.

   - The number of filters in a Conv2D-layer can be chosen arbitrarily: 
   True. 
   The number of filters in a Conv2D layer can be set to any value, and it depends on the specific problem and architecture being used. 
   A larger number of filters increases the capacity of the network to learn complex features, but also increases the computational cost.

   - The width and height of a Conv2D-layer output can be chosen arbitrarily: 
   False. 
   The size of the output from a Conv2D layer depends on the parameters used, such as padding, strides, and kernel size. 
   If "valid" padding is used, the output size will be smaller than the input size. If "same" padding is used, 
   the output size will be the same as the input size. The stride determines how the filter moves across the input, and can also affect the size of the output.

   - A max-pooling layer must have a kernel size of 2x2: 
   False. 
   The kernel size of a max-pooling layer can be any size, 
   but 2x2 is a common choice because it has been found to work well in practice and reduces the spatial dimensions of the data efficiently.

   - A Conv2D-layer must be followed by ReLU: 
   False. 
   There is no requirement that a Conv2D layer must be followed by ReLU. 
   Different activation functions can be used depending on the specific architecture being used. 
   ReLU is a commonly used activation function because it is simple and has been found to work well in practice.

   - A CNN classifier must contain at least one affine layer: 
   True. 
   An affine layer, also known as a dense layer, is typically used for the final classification in a CNN classifier. 
   The output from the Conv2D and max-pooling layers is typically flattened into a 1D tensor, and then passed through one or more dense layers for the final classification.

   - A CNN classifier can contain an arbitrary number of Conv2D-layers: 
   True. 
   There is no limit to the number of Conv2D layers that can be used in a CNN classifier. 
   The number of Conv2D layers used depends on the specific problem and architecture being used. 
   A deep network with many Conv2D layers can learn complex features, but also increases the computational cost and can lead to overfitting.



Advanced numpy
For-loops are forbidden here!!

a) Give a code snippet that create two random 1D arrays of length 20, with
integer entries between 0 and 3 (included). Then, the code should compute the
confusion matrix from these two vectors.

b) Give a code snippet that generates two 1D arrays with values from 0 to 19
(included) in ascending order. Then, the code should shuffle both arrays such
that same positions contain same values after shuffling (like you would shuffle
train data and labels).

c) Give a code snippet that creates a 1D array with random values from 0 to
9 (included). Then, interpret this array as scalar targets and create a one-hot
representation for them, assuming 10 classes.

In [3]:
import numpy as np

# Create two random 1D arrays of length 20 with integer entries between 0 and 3
y_true = np.random.randint(0, 4, 20)
y_pred = np.random.randint(0, 4, 20)
print(y_true, y_pred)
# Compute the confusion matrix using np.add.at and without using a for-loop
confusion_matrix = np.zeros((4, 4), dtype=int)
np.add.at(confusion_matrix, (y_true, y_pred), 1)

print(confusion_matrix)

[2 3 2 1 3 3 2 2 0 3 1 3 0 2 3 0 2 3 2 3] [0 3 3 1 2 1 2 3 2 2 2 1 1 0 0 2 3 1 1 2]
[[0 1 2 0]
 [0 1 1 0]
 [2 1 1 3]
 [1 3 3 1]]


In [4]:
import numpy as np

# Generate two 1D arrays with values from 0 to 19 in ascending order
a = np.arange(20)
b = np.arange(20)

# Generate a random permutation of indices
permutation = np.random.permutation(20)

# Shuffle both arrays such that same positions contain same values after shuffling
a = a[permutation]
b = b[permutation]

print(a)
print(b)


[ 9  5 18  6 11 16  1 13  2 12 19  7 10 14 17  4  0  8  3 15]
[ 9  5 18  6 11 16  1 13  2 12 19  7 10 14 17  4  0  8  3 15]


In [5]:
import numpy as np

# Create a 1D array with random values from 0 to 9 (included)
targets = np.random.randint(0, 10, size=(20,))

# Create a one-hot representation for the targets, assuming 10 classes
one_hot_targets = np.zeros((20, 10))
one_hot_targets[np.arange(20), targets] = 1

print(targets)
print(one_hot_targets)

[8 5 3 9 3 0 6 7 6 4 7 5 0 0 1 8 1 6 7 5]
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


Probabilities

Consider these experimental results for X and Y:
Exp 1 (X): 1 1 1 1 2 2 2 2 1 1 1 1
Exp 2 (Y): 2 1 1 2 1 2 3 1 3 1 1 3 
Compute:
a) #(Y = 1), #(Y = 2), #(Y = 3)
b) #(X = 1, Y = 1), #(X = 1, Y = 2), #(X = 1, Y = 3)
c) p(X = 1, Y = 1), p(X = 1, Y = 2), p(X = 1, Y = 3)
d) p(X = 1|Y = 1), p(X = 1|Y = 2), p(X = 1|Y = 3)
e) p(Y = 1|X = 1)
f ) p(X = 1|Y ̸ = 1)

a) 6        3       3
b) 4        2       2
c) 4/12     2/12    2/12
d) 4/6      2/3     2/3
e) 4/8
f ) 4/6

Confusion matrix

Evaluation of a classifier yields the following CM:

10 60 10
0 80 0
0 20 60

Compute:
a) Nr of test samples
b) p(ˆy = 1|ˆt = 2)
c) p(ˆt = 1), p(ˆt = 2), p(ˆy = 2)
d) Probability of an incorrect classification when restricting ourselves to classifer outputs of 2.
e) Probability of an incorrect classification
 y = แนวนอน t = แนวตั้ง start at 1 

a) sum all
10 + 60 + 10 + 0 + 80 + 0 + 0 + 20 + 60 => 240
b) 
0 / 0 + 80 + 0 = 0
c) 
10 + 60 + 10 / 240 = 80/240, 
0 + 80 + 0 / 240 = 80/240, 
60 + 80 + 20 / 240 = 160/240
d) p(y^ != t^ | y^ = 2) 
60 + 20 / 160 = 80/160
e) (y^ != t^)
60 + 10 + 0 + 0 + 0 + 20 / 240 = 90/240


Binary Classification 1

A binary classifier that always chooses the negative class is evaluated on a test
set in which the proportion between positive and negative samples as 1:9. Com-
pute:
a) tpr, fnr
b) fpr, tnr
c) classification error