Array creation
Useful functions for array creation (look them up): np.arange, np.linspace,
np.random.uniform, Python list comprehension. Nested Python lists are con-
verted into numpy arrays in row-wise fashion!
a) Create a 1D array with entries from 0 to 100 in steps of 2
b) Create a 2D array with 3 rows and 3 columns, with row entries 1,1,1...,
2,2,2,..., 3,3,3,...
c) Create a 2D array with 3 rows and 5 columns that has the value 55 every-
where
d) Create a 3D tensor with shape (5,4,3) with uniform random entries between
0 and 1.

In [3]:
import numpy as np

a = np.arange(0, 101, 2)  # assume that 100 is included
a

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [8]:
# b1) both solutions are equivalent
# b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
b = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3]).reshape(3, 3)
b

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [11]:
# b2) principled solution for large arrays using broadcasting, 10x10 array
# create a 1d vector with entries from 1 to 3 included
rowCoeffs = np.arange(1, 11, 1)
b2 = np.ones([10, 10]) * rowCoeffs.reshape(10, 1)  # use broadcasting!!
b2

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [13]:
# c)
c = np.ones([3, 5]) * 55
c

array([[55., 55., 55., 55., 55.],
       [55., 55., 55., 55., 55.],
       [55., 55., 55., 55., 55.]])

In [14]:
# d)
d = np.random.uniform(0, 1, (5, 4, 3))
d
d = np.random.uniform(0, 1, 60).reshape(5, 4, 3)
d

array([[[0.65192383, 0.71507226, 0.12835938],
        [0.1724288 , 0.68535694, 0.16237254],
        [0.64682395, 0.27556021, 0.76204235],
        [0.20485278, 0.5900433 , 0.12694713]],

       [[0.25766719, 0.7945664 , 0.05149798],
        [0.88676825, 0.04536609, 0.58876992],
        [0.14740551, 0.83857857, 0.68842952],
        [0.71951952, 0.86334819, 0.93290698]],

       [[0.57862749, 0.43060179, 0.84576706],
        [0.62616318, 0.09715811, 0.54787897],
        [0.96931713, 0.52890099, 0.38700097],
        [0.94212389, 0.46507923, 0.68519474]],

       [[0.09952078, 0.47892343, 0.88773905],
        [0.27810141, 0.50403114, 0.5268803 ],
        [0.58036252, 0.56091804, 0.54714327],
        [0.09648634, 0.82848265, 0.38619173]],

       [[0.90300552, 0.42822846, 0.34992642],
        [0.18537155, 0.10543446, 0.13338855],
        [0.44603479, 0.4439346 , 0.28843971],
        [0.60962236, 0.62833718, 0.3159443 ]]])

Numpy basics and slicing
Assume that the 3D array ’traind’ contains 2000 images of dimension 20x20.
You can, e.g., generate it using
traind = np.random.uniform(0,255,[2000,20,20]).
Give code snippets for the following operations and print out the results for
verification:
a) Slice out the 1000th sample into an array x and print it!
b) Set the 5 topmost and the 5 lowermost columns of sample 1000 to 0
c) Print the smallest and highest pixel value in the 10th data sample
e) Generate the following variations of the 10th sample and store them in a new
variable z:
- just keep every 2nd row
- just keep every 2nd column
- inverse all rows and all columns
- invert rows, invert colums, just take every 2th row and every 2th column
f ) Apply the in-place transform
1 − x
to all samples.

In [27]:
# stack of 2D images of dimensions 20x20
traind = np.random.uniform(0, 255, [2000, 20, 20])

# a)
a = traind[999, :, :]
a = traind[999]    # equivalent!
a

# b) set topmost and lowermost rows to 0
# rows
a[0:5, :] = 0
a[15:, :] = 0

a

# c)
# slice out sample/image nr 10
c = traind[9]
c.min()
c.max()

# d)
d1 = c[::2, :]  # or c[::2]
d2 = c[:, ::2]
d3 = c[::-1, ::-1]
d4 = c[::-2, ::-2]

# f) # in-place
traind *= -1
traind += 1
# BAD: copy created and original array is discarded
traind = 1-traind


254.7499354533534

Reduction
Take the array ‘traind’ from the previous exercise and perform the following
transformations. Useful functions: ndarray.mean, ndarray.sum, ndarray.min.
a) Compute the pixel sum for pixel 0,0 over all samples
b) Compute the pixel mean for pixel 0,0 over all samples
c) Compute the image mean over all samples
d) Compute the row-wise max over all samples
e) Compute the row-wise sum over all samples

In [34]:
# stack of 2D images of dimensions 20x20
traind = np.random.uniform(0, 255, [2000, 20, 20])
# a)
a = np.sum(traind[:, 0, 0])
# b)
b = np.mean(traind[:, 0, 0])
# c)
c = np.mean(traind, axis=0)
# d)
d = traind.max(axis=2)
# e)
e = traind.sum(axis=2)

e

array([[2744.48130584, 2453.08527461, 2236.01541524, ..., 2483.58950394,
        2410.34516363, 2455.60924057],
       [2225.9109958 , 2669.94889223, 2309.55334436, ..., 2431.38750318,
        2165.21961513, 2160.38323796],
       [1988.20712079, 2194.51767574, 2105.7256818 , ..., 2356.87151684,
        2897.77444741, 2626.78864386],
       ...,
       [2269.66168894, 2548.37600885, 2413.04474879, ..., 2177.80594943,
        2351.17406757, 2471.47158088],
       [2399.36892252, 2235.02694373, 2703.21729619, ..., 2347.5178413 ,
        2551.10261044, 2573.21561508],
       [2743.27824121, 2213.40720826, 2771.68797908, ..., 2502.83792773,
        2266.18777985, 2132.10120248]])

Broadcasting
Using ‘traind’ from ex. 1 and perform the following transformations. np.reshape
is useful here to insert extra dimensions of size 1 if needed!
a) create a 20-element vector with entries from 1 to 20, and add it to all rows
of all samples using broadcasting
b) create a 20-element vector with entries from 1 to 20, and add it to all
columns of all samples using broadcasting
c) add sample 0 to all other samples of ‘traind’.

In [35]:
# stack of 2D images of dimensions 20x20
traind = np.random.uniform(0, 255, [2000, 20, 20])

vec = np.arange(1, 21, 1)
# a)
traind += vec.reshape(1, 1, 20)
# b)
traind += vec.reshape(1, 20, 1)
# c)
traind += traind[0].reshape(1, 20, 20)

Fancy indexing and mask indexing
a) create a 20-element vector with entries from 1 to 20, and copy out all
elements that are smaller than 10 using mask indexing!
b) create a 20-element vector with entries from 1 to 20, and set elements 1,5
and 19 to 0 using fancy indexing!

In [38]:
vec = np.arange(1, 21, 1)
# a)
smaller = vec[(vec < 10)]
# b)
vec[[1, 5, 19]] = 0

smaller
vec

array([ 1,  0,  3,  4,  5,  0,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19,  0])