In [5]:
import numpy as np
digits = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [6, 7, 9],
])

digits


array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 9]])

In [7]:
import numpy as np

CURVE_CENTER = 80

grades = np.array([72, 35, 64, 88, 51, 90, 74, 12])

def curve(grades):

    average = grades.mean()

    change = CURVE_CENTER - average

    new_grades = grades + change

    return np.clip(new_grades, grades, 100)


curve(grades)



array([ 91.25,  54.25,  83.25, 100.  ,  70.25, 100.  ,  93.25,  31.25])

In [34]:
import numpy as np

temperatures = np.array([
    29.3, 42.1, 18.8, 16.1, 38.0, 12.5,
    12.6, 49.9, 38.6, 31.3, 9.2, 22.2
]).reshape(2, 2, 3)

temperatures

temperatures.shape

temperatures
# np.swapaxes(temperatures, 1, 2)


array([[[29.3, 42.1, 18.8],
        [16.1, 38. , 12.5]],

       [[12.6, 49.9, 38.6],
        [31.3,  9.2, 22.2]]])

In [36]:
import numpy as np

table = np.array([
    [5, 3, 7, 1],
    [2, 6, 7 ,9],
    [1, 1, 1, 1],
    [4, 3, 2, 0],
])

table.max()


table.max(axis=0)


# table.max(axis=1)

array([5, 6, 7, 9])

In [41]:
import numpy as np

A = np.arange(32).reshape(4, 1, 8)

B = np.arange(48).reshape(1, 6, 8)

(A + B).shape

(4, 6, 8)

In [47]:
import numpy as np

numbers = np.linspace(5, 50, 24, dtype=int).reshape(4, -1)

numbers

mask = numbers % 4 == 0

mask

numbers[mask]

by_four = numbers[numbers % 4 == 0]

by_four

array([ 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])